general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 20

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\b\r"
